<?php

/**
 * BaseRecurringExpense
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $date_of_payment
 * @property string $name
 * @property string $description
 * @property decimal $amount
 * @property enum $recurring_type
 * 
 * @method date             getDateOfPayment()   Returns the current record's "date_of_payment" value
 * @method string           getName()            Returns the current record's "name" value
 * @method string           getDescription()     Returns the current record's "description" value
 * @method decimal          getAmount()          Returns the current record's "amount" value
 * @method enum             getRecurringType()   Returns the current record's "recurring_type" value
 * @method RecurringExpense setDateOfPayment()   Sets the current record's "date_of_payment" value
 * @method RecurringExpense setName()            Sets the current record's "name" value
 * @method RecurringExpense setDescription()     Sets the current record's "description" value
 * @method RecurringExpense setAmount()          Sets the current record's "amount" value
 * @method RecurringExpense setRecurringType()   Sets the current record's "recurring_type" value
 * 
 * @package    pers
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRecurringExpense extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('recurring_expense');
        $this->hasColumn('date_of_payment', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('amount', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('recurring_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'daily',
              1 => 'weekly',
              2 => 'monthly',
              3 => 'bi-monthly',
              4 => 'quarterly',
              5 => 'half-yearly',
              6 => 'annually',
              7 => 'bi-annually',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
        $this->actAs($signable0);
    }
}