<?php

/**
 * BaseIncome
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $date
 * @property string $name
 * @property string $description
 * @property decimal $amount
 * 
 * @method date    getDate()        Returns the current record's "date" value
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method decimal getAmount()      Returns the current record's "amount" value
 * @method Income  setDate()        Sets the current record's "date" value
 * @method Income  setName()        Sets the current record's "name" value
 * @method Income  setDescription() Sets the current record's "description" value
 * @method Income  setAmount()      Sets the current record's "amount" value
 * 
 * @package    pers
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIncome extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('income');
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('amount', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
        $this->actAs($signable0);
    }
}