generator:
  class: sfDoctrineGenerator
  param:
    model_class:           RecurringExpense
    theme:                 redminish
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          recurring_expense
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
         display: [id, date_of_payment, name, description, recurring_type, amount ]
      filter:  
        display: [date_of_payment, name, description, recurring_type, amount ]
      form:    
        display: [date_of_payment, name, description, recurring_type, amount ]
      edit:    ~
      new:     ~
