recurring_expense:
  class: sfDoctrineRouteCollection
  options:
    model:                RecurringExpense
    module:               recurring_expense
    prefix_path:          /recurring_expense
    column:               id
    with_wildcard_routes: true

income:
  class: sfDoctrineRouteCollection
  options:
    model:                Income
    module:               income
    prefix_path:          /income
    column:               id
    with_wildcard_routes: true

expense:
  class: sfDoctrineRouteCollection
  options:
    model:                Expense
    module:               expense
    prefix_path:          /expense
    column:               id
    with_wildcard_routes: true


# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: dashboard, action: index }
  
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

logout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
