<?php

/**
 * ExpenseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExpenseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExpenseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Expense');
    }
    
    public function findLatestQuery()
   {
       return $this->createQuery()
                ->orderBy('date DESC');
   }
}