<?php

/**
 * IncomeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IncomeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IncomeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Income');
    }
    
    
    public function findLatestQuery()
    {
        return $this->createQuery()
                ->orderBy('date DESC');
    }
}