<?php

/**
 * RecurringExpenseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecurringExpenseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecurringExpenseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RecurringExpense');
    }
}