generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Income
    theme:                 redminish
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          income
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
         display: [id, date, name, description, amount ]
      filter:  
         display: [date, name, description, amount ]
      form:    
         display: [date, name, description, amount ]
      edit:    ~
      new:     ~
